# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  builddocker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: mr-smithers-excellent/docker-build-push@v5.6
        name: Build & push Docker image
        with:
          image: docker2706/itea
          tags: v1, latest
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
